### ISSUE TITLE
[Issue] Modal dialog owner always MainWindow

### ISSUE THREAD

**Issue by SD-alexander-bittermann** [AvaloniaCommunity/Prism.Avalonia#74] opened 2023-06-02 22:43 UTC
## Description
When showing a modal dialog the owner is always set to MainWindow instead of the window it was opened from, which leads to problems when the modal dialog is opened from another dialog.

## Environment
* **OS:**  Windows 10
*  **Prism.Avalonia Version:** 8.1.97.2
* **Avalonia Version:** 0.10.21 

## Severity (1-5)
3

## Steps To Reproduce
1. Open modal dialog from another dialog via dialogService.ShowDialog()

## Expected Behavior
Owner of the modal dialog should be set to the owning window and not to MainWindow so that the acutal owning window can not be interacted with while the modal dialog is open.

[DialogService](https://github.com/AvaloniaCommunity/Prism.Avalonia/blob/b5aa9ffede60b7c3c426cc30fa34119932636223/src/Prism.Avalonia/Services/Dialogs/DialogService.cs#L104)

**Comment by DamianSuess** [comment] 2023-06-02 23:37
@SD-alexander-bittermann, though unfortunate, nice find.
I created a test branch, `feature/Avalonia-v10-DialogHostWin`, and was able to reproduce your issue. Prioritizing this on the backlog.

Thank you

**Comment by DamianSuess** [comment] 2023-06-03 00:30
Just a heads up for why it was implemented this way, Avalonia, unlike WPF, requires a `Window` to be passed into the `.ShowDialog()` method. I.E. WPF uses `_dialogService.ShowDialog();` and Avalonia requires `_dialogService.ShowDialog(owner: hostWindow);`

**Comment by DamianSuess** [comment] 2023-06-03 15:00
Made a change to the API to allow for an optional Parent window to be passed to the `DialogService.ShowDialog(...)` method. Now users can chain together modal windows.  I'm going to keep testing and validating this before merging it in.

![image](https://github.com/AvaloniaCommunity/Prism.Avalonia/assets/1216684/8d76309a-37c0-439e-a4cd-f330f2b43018)

**Comment by DamianSuess** [comment] 2023-06-03 22:17
This issue has been resolved and merged into [stable/v8.1.97.10xx](https://github.com/AvaloniaCommunity/Prism.Avalonia/tree/stable/v8.1.97.10xx)

There are still more enhancements on the backlog which needs to be made a new NuGet is published. It will be out in the upcoming week(s). No later than 2023-Q2 (end of this month)

**Comment by SD-alexander-bittermann** [comment] 2023-06-05 05:34
Thank you very much for the quick correspondence!

**Comment by DamianSuess** [comment] 2023-06-15 00:02
@SD-alexander-bittermann, i'm going to go ahead and close this issue out as the code fix has been merged into the code base for both Avalonia v0.10.x and v11.x, with the package coming at the end of Q2.

Thank you again for bringing this up!

**Closed by DamianSuess** 2023-06-15 00:02 UTC
Labels: bug, Avalona-v0.10.x, Avalonia-v11.0.x

**Comment by DamianSuess** [comment] 2023-07-10 18:39
@AlexBittermann, I will cherry-pick it into the v0.10.x this week.
For anyone else wondering, it did get published into the latest [v8.1.97.11000](https://www.nuget.org/packages/Prism.Avalonia/) release for Avalonia v11.0

**Comment by AlexBittermann** [comment] 2023-07-31 19:34
@DamianSuess Still hoping for a v0.10.x package

**Comment by AlexBittermann** [comment] 2023-08-08 08:06
@DamianSuess 
I don't want to be annoying but I'm still waiting for the v0.10.x package since I need this fix for my project
